service: qualitia-download
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

plugins:
  - serverless-dotenv-plugin
  - serverless-pseudo-parameters

functions:
  oauth:
    handler: oauth/lambda.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
    environment:
      OAUTH_CLIENT_ID: ${env:OAUTH_CLIENT_ID}
      OAUTH_CLIENT_SECRET: ${env:OAUTH_CLIENT_SECRET}
      AUTH_SERVICE_URL: https://#{ApiGatewayRestApi}.execute-api.#{AWS::Region}.amazonaws.com/${self:provider.stage}

# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
