service: qualitia-download
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221    

plugins:
  - serverless-dotenv-plugin
  - serverless-pseudo-parameters
  - serverless-iam-roles-per-function

functions:
  download:
    handler: download/lambda.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
    environment:
      OAUTH_CLIENT_ID: ${env:OAUTH_CLIENT_ID}
      OAUTH_CLIENT_SECRET: ${env:OAUTH_CLIENT_SECRET}
      BUCKET: qualitia-installer
      AUTH_SERVICE_URL: https://#{ApiGatewayRestApi}.execute-api.#{AWS::Region}.amazonaws.com/${self:provider.stage}
    iamRoleStatements:
      - Effect: Allow
        Action: 
          - "s3:ListBucket"
        Resource: "arn:aws:s3:::qualitia-installer"